fabian-hiller/valibot

library/src/methods/coerce/coerce.ts, library/src/methods/coerce/coerceAsync.ts, library/src/methods/parse/parse.ts, library/src/methods/parse/parseAsync.ts, library/src/methods/partial/partial.ts, library/src/methods/partial/partialAsync.ts, library/src/methods/required/required.ts, library/src/methods/required/requiredAsync.ts, library/src/methods/safeParse/safeParse.ts, library/src/methods/safeParse/safeParseAsync.ts, library/src/methods/transform/transform.ts, library/src/methods/transform/transformAsync.ts, library/src/methods/useDefault/useDefault.ts, website/src/routes/guides/(get-started)/introduction/index.mdx
Hi, first of all, thanks for a nice library!
This pull request fixes a typo: scheme -> schema.
=> Doc: fix typo of schema

library/src/validations/url/url.ts
=> Fix typo in url.ts

library/src/utils/index.ts, library/src/utils/isLuhnAlgo/index.ts, library/src/utils/isLuhnAlgo/isLuhnAlgo.test.ts, library/src/utils/isLuhnAlgo/isLuhnAlgo.ts, library/src/validations/imei/imei.test.ts, library/src/validations/imei/imei.ts, library/src/validations/imei/index.ts, library/src/validations/index.ts, website/src/routes/api/(validations)/imei/index.mdx, website/src/routes/api/menu.md
Creates a validation functions that validates a IMEI (International Mobile Equipment Identity).
INFO: https://en.wikipedia.org/wiki/International_Mobile_Equipment_Identity
[x]: tests added
[x]: docs placeholder added
=> feature: IMEI validation

library/src/validations/index.ts, library/src/validations/integer/index.ts, library/src/validations/integer/integer.test.ts, library/src/validations/integer/integer.ts
I noticed that the project lacks a validation function for integer values, while other validation libraries typically support this feature. Therefore, I have implemented a new validation function to check for integer values.
=> feature: integer validation

website/src/routes/guides/(main-concepts)/parse-data/index.mdx
=> Updated index.mdx

website/src/routes/guides/(main-concepts)/schemas/index.mdx
=> Fix a typo in index.mdx

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Here's the utility that I had mentioned I built for integration with NestJS. If you need any modifications let me know.
=> docs: add nestjs and nest-lab/validation to the ecosystem

website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Updated `StringSchema` documentation for `getOutput` and `getPipeIssues` changes
=> docs: StringSchema update

library/CHANGELOG.md, library/src/validations/notValue/notValue.ts
Since value accepts boolean, this PR adds support for booleans to not value.
also fix date missing while available in types
=> fix(not-value): allow not value to accept booleans

website/src/routes/api/(schemas)/date/index.mdx, website/src/routes/api/(types)/DateSchema/index.mdx, website/src/routes/api/menu.md
Implementing Date schema docs as discussed in https://github.com/fabian-hiller/valibot/issues/287
=> docs(api): add and fill date schema docs

website/src/routes/guides/(advanced)/naming-convention/index.mdx
The comma is unnecessary here and makes the sentence harder to read / understand
=> docs: removed comma

library/src/validations/startsWith/startsWith.ts
=> fix: starts_with typo

website/src/routes/guides/(get-started)/ecosystem/index.mdx
I created a form library called [Conform](https://github.com/edmundhung/conform) that can be parsed using Valibot's schema.
I added the library I created to the ecosystem documentation.
=> docs: Add new Valibot schema parser for conform to document of ecosystem

website/src/routes/guides/(schemas)/objects/index.mdx
**Before**
```ts
import * as v from 'valibot';
const CalculationSchema = v.object(
{
a: v.number(),
b: v.number(),
sum: v.number(),
},
[
forward(
v.custom(
({ a, b, sum }) => a + b === sum,
'The calculation is incorrect.'
),
['sum']
),
]
);
```
**After**
```ts
import * as v from 'valibot';
const CalculationSchema = v.object(
{
a: v.number(),
b: v.number(),
sum: v.number(),
},
[
v.forward(
v.custom(
({ a, b, sum }) => a + b === sum,
'The calculation is incorrect.'
),
['sum']
),
]
);
```
=> docs: update code examples to fix incorrect `forward` call

website/src/routes/guides/(migration)/migrate-to-v0.31.0/index.mdx
=> Fix typo "togehter" -> "together"

.grit/patterns/migrate_to_v0_31_0.md
fixes https://github.com/fabian-hiller/valibot/issues/621
=> fix: migrate object and tuples with grit

.grit/patterns/migrate_to_v0_31_0.md
Per discussion: https://github.com/fabian-hiller/valibot/pull/625#issuecomment-2147168690
=> fix: transform schemas with additional arguments

website/src/routes/guides/(main-concepts)/schemas/index.mdx
I found some incorrect schema definitions in the code examples and have corrected them.
=> docs: fix schemas

website/src/routes/guides/(migration)/migrate-from-zod/index.mdx
=> Update index.mdx: fix grammar

website/src/routes/api/(async)/setAsync/index.mdx, website/src/routes/api/(async)/setAsync/properties.ts, website/src/routes/api/(types)/SetSchemaAsync/index.mdx, website/src/routes/api/(types)/SetSchemaAsync/properties.ts, website/src/routes/api/menu.md
This PR adds `setAsync` and `SetSchemaAsync` API references to the website.
=> add `setAsync` & `SetSchemaAsync` API refs

website/src/routes/api/(types)/CheckAction/index.mdx, website/src/routes/api/(types)/CheckAction/properties.ts
Improvements:
- match the JSDoc description.
- constraint `TInput` type parameter to `any`.
=> improve `CheckAction` API ref

website/src/routes/api/(async)/tupleAsync/index.mdx, website/src/routes/api/(async)/tupleAsync/properties.ts, website/src/routes/api/(types)/TupleSchemaAsync/index.mdx, website/src/routes/api/(types)/TupleSchemaAsync/properties.ts, website/src/routes/api/menu.md
https://github.com/fabian-hiller/valibot/issues/287
=> Doc: add tupleAsync docs

website/src/routes/api/(async)/strictTupleAsync/index.mdx, website/src/routes/api/(async)/strictTupleAsync/properties.ts, website/src/routes/api/(types)/StrictTupleSchemaAsync/index.mdx, website/src/routes/api/(types)/StrictTupleSchemaAsync/properties.ts, website/src/routes/api/menu.md
https://github.com/fabian-hiller/valibot/issues/287
=> Doc: add strictTupleAsync doc

website/src/routes/api/(async)/looseTupleAsync/index.mdx, website/src/routes/api/(async)/looseTupleAsync/properties.ts, website/src/routes/api/(types)/LooseTupleSchema/properties.ts, website/src/routes/api/(types)/LooseTupleSchemaAsync/index.mdx, website/src/routes/api/(types)/LooseTupleSchemaAsync/properties.ts, website/src/routes/api/menu.md
https://github.com/fabian-hiller/valibot/issues/287
=> Doc: add looseTupleAsync doc

website/src/routes/api/(async)/tupleWithRestAsync/index.mdx, website/src/routes/api/(async)/tupleWithRestAsync/properties.ts, website/src/routes/api/(types)/TupleWithRestSchema/index.mdx, website/src/routes/api/(types)/TupleWithRestSchema/properties.ts, website/src/routes/api/(types)/TupleWithRestSchemaAsync/index.mdx, website/src/routes/api/(types)/TupleWithRestSchemaAsync/properties.ts, website/src/routes/api/menu.md
https://github.com/fabian-hiller/valibot/issues/287
Additionally, I added some properties missing on `TupleWithRestSchema`.
=> Doc: add tupleWithRestAsync doc

website/src/routes/guides/(get-started)/ecosystem/index.mdx
[valiload](https://github.com/JuerGenie/valiload)
=> docs: add `valiload` to ecosystem list

website/src/routes/api/(schemas)/picklist/index.mdx
Self-explanatory quick typo fix.
=> Fix typo in picklist docs

website/src/routes/guides/(get-started)/ecosystem/index.mdx
This pull request adds a link to the @rvf/valibot package in the documentation
=> docs: add @rvf/valibot to guides/ecosystem 

website/src/routes/guides/(main-concepts)/parse-data/index.mdx
Just some simple grammar mistakes.
=> Updated grammar in index.mdx

website/src/routes/guides/(main-concepts)/methods/index.mdx
=> little typo

website/src/routes/guides/(get-started)/ecosystem/index.mdx
I've seen @fabian-hiller 's 💌  https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/779
Thank you so much!
=> added graphql-codegen-typescript-validation-schema in ecosystem

website/src/routes/api/(types)/VariantIssue/index.mdx
=> Fix VariantIssue mdx: issues property not exist

website/src/routes/playground/index.tsx
=> feat: Auto-scroll playground's logs container to the latest log message

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Related: https://github.com/unnoq/orpc/discussions/276
=> docs: add oRPC to Ecosystem

website/src/routes/api/(methods)/pick/index.mdx
Just a minor fix to a sentence that is a little hard to read :)
=> Fix sentence structure in `pick` documentation

library/CHANGELOG.md, library/src/actions/multipleOf/multipleOf.test-d.ts, library/src/actions/multipleOf/multipleOf.test.ts, library/src/actions/multipleOf/multipleOf.ts, library/src/utils/_stringify/_stringify.ts, website/src/routes/api/(actions)/multipleOf/index.mdx, website/src/routes/api/(actions)/multipleOf/properties.ts, website/src/routes/api/(schemas)/bigint/index.mdx, website/src/routes/api/(types)/MultipleOfAction/properties.ts, website/src/routes/api/(types)/MultipleOfIssue/index.mdx, website/src/routes/api/(types)/MultipleOfIssue/properties.ts
=> Add support for bigints to multipleOf validation action

.github/actions/environment/action.yml, website/src/components/CodeEditor.tsx, website/src/routes/playground/index.tsx, website/vercel.json
=> Add to-json-schema package to playground of website
