fabian-hiller/valibot

website/src/routes/api/(schemas)/union/index.mdx
As it's a tiny copy paste miss, I didn't open a issue for it.
=> chore(docs): fix typo in union document page

website/src/routes/guides/(get-started)/ecosystem/index.mdx
vee-validate v4.11.0 now supports valibot as a schema provider
Relevant [doc link](https://vee-validate.logaretm.com/v4/guide/composition-api/getting-started/#validating-with-valibot).
Thanks for building this and cheers!
=> docs: added vee-validate in ecosystem form libraries section

website/src/routes/guides/(main-concepts)/schemas/index.mdx
This updates the typo `tuble` to `tuples` in the docs.
=> Rename `tuble` to `tuples` in index.mdx

website/src/routes/guides/(main-concepts)/methods/index.mdx
=> Rename `offers` to `offer` in index.mdx

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Following up on https://github.com/decs/typeschema/issues/11, this pull request lists TypeSchema on the ecosystem page
=> docs: add typeschema to ecosystem

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Hono now includes support for Valibot (https://github.com/honojs/middleware/pull/102) so we should add it to the list.
Thanks for your work!
=> docs: add Hono to ecosystem page

library/src/validations/isoDateTime/isoDateTime.test.ts, library/src/validations/isoDateTime/isoDateTime.ts, library/src/validations/isoTime/isoTime.test.ts, library/src/validations/isoTime/isoTime.ts, library/src/validations/isoTimeSecond/isoTimeSecond.test.ts, library/src/validations/isoTimeSecond/isoTimeSecond.ts, library/src/validations/isoTimestamp/isoTimestamp.test.ts, library/src/validations/isoTimestamp/isoTimestamp.ts
The existing ISO timestamp validations only allowed `01`-`09` for hours, but not `00`. This fixes that.
=> Fix ISO validation hours to allow `00`

website/src/routes/guides/(main-concepts)/infer-types/index.mdx
Fixed missing import, as it seems like it's a custom function and not a part of valibot
=> docs: added missing transform to imports

library/src/schemas/record/record.test.ts, library/src/schemas/record/record.ts
This pull request addresses a critical issue in the current record schema that makes it susceptible to prototype pollution. The vulnerability arises due to the lack of key validation, allowing certain keys to be exploited, leading to potential security risks.
To mitigate this vulnerability, I have implemented a key blacklisting mechanism. By doing so, specific keys prone to prototype pollution are disallowed within the record schema.
=> security: Mitigate Prototype Pollution Vulnerability

.github/workflows/node.yml
Currently, CI does not run in all pull requests. In fact, the only time it runs is when the branch of the forked repository also happens to be named `main` (i.e., the default branch). Since it is generally a best practice to branch out of `main` even in a fork, resulting PRs back into Valibot does not trigger CI.
This PR simply removes the `main` branch restriction on the `pull_request` hook for GitHub Actions, thereby allowing the `node` workflow to run in PRs.
=> fix(ci): enable CI on pull requests

library/src/schemas/array/array.ts, library/src/schemas/object/object.ts, library/src/schemas/record/record.ts, library/src/schemas/record/recordAsync.ts, library/src/schemas/record/values.ts, library/src/schemas/tuple/tuple.ts, library/src/utils/executePipe/executePipe.ts
Following #67, this PR swaps the container of `BLOCKED_KEYS` from a `Set` into an `Array`. This is because although `Set#has` is $O(1)$, the constant coefficient for this is actually quite expensive due to underlying hashing algorithms. In comparison, the $O(n)$ function `Array#includes` should be faster **for small arrays** for the following reasons:
1. `Array#includes` is a built-in method which does not perform any hashing.
2. With its elements being collocated, arrays are typically friendlier to the CPU cache. This is not the case for sets whose elements are sparsely located in a buffer.
In the case of `BLOCKED_KEYS`, three elements are certainly sufficiently small to justify the linear search. See the discussion in https://github.com/fabian-hiller/valibot/pull/67#discussion_r128523215 …
=> refactor(record): prefer arrays over sets for lookups of blocked keys

website/src/routes/guides/(main-concepts)/methods/index.mdx
=> fix(typo): "pare data" => "parse data"

library/CHANGELOG.md, library/src/schemas/literal/index.ts, library/src/schemas/literal/literal.test.ts, library/src/schemas/literal/literal.ts, library/src/schemas/literal/literalAsync.test.ts, library/src/schemas/literal/literalAsync.ts, library/src/schemas/literal/types.ts
This PR add all primitives values on literal schema.
Solve Issue #97
=> Primitives values in literal schema

library/CHANGELOG.md, library/src/methods/fallback/fallback.test.ts, library/src/methods/fallback/fallback.ts, library/src/methods/fallback/fallbackAsync.test.ts, library/src/methods/fallback/fallbackAsync.ts, library/src/methods/fallback/index.ts, library/src/methods/fallback/types.ts, library/src/methods/index.ts, library/src/methods/withDefault/withDefault.test.ts, website/src/routes/api/(methods)/fallback/index.mdx, website/src/routes/guides/(main-concepts)/methods/index.mdx
Now that exceptions are gone, I can finally, properly implement the `fallback` method. #74 
Also added some tests.
Still not sure about the issues that are caught though. Adding a centralized way to collect these warning, just for fallback, is unnecessary. Printing or being able to receive them through the callback might work for now, but I did not try collecting them.
=> Fallback method

library/src/methods/transform/transformAsync.ts
I can't do
```typescript
transformAsync(instance(File), async (input) => {
return file.length;
});
```
but 
```typescript
transform(instance(File), async (input) => {
return file.length;
});
```
is working
=> fix: add InstanceSchema to transformAsync

library/CHANGELOG.md, library/src/methods/parse/parse.ts, library/src/methods/parse/parseAsync.ts, library/src/methods/safeParse/safeParse.ts, library/src/methods/safeParse/safeParseAsync.ts, library/src/schemas/map/map.ts, library/src/schemas/map/mapAsync.ts, library/src/schemas/record/record.ts, library/src/schemas/record/recordAsync.ts, library/src/types.ts, library/src/utils/executePipe/executePipe.test.ts, library/src/utils/executePipe/executePipe.ts, library/src/utils/executePipe/executePipeAsync.test.ts, library/src/utils/executePipe/executePipeAsync.ts, library/src/utils/executePipe/utils/getIssue/getIssue.ts, library/src/utils/executePipe/utils/getPipeInfo/getPipeInfo.ts, library/src/utils/getSchemaIssues/getSchemaIssues.ts, website/src/routes/guides/(main-concepts)/errors/index.mdx, website/src/routes/guides/(main-concepts)/parse-data/index.mdx
Firstly, thanks for Valibot 😊 It's a great library and I'm excited to use it in projects moving forward! 
When validating a value, it would be useful to be able to confirm the type of the object without throwing if the values don't pass formatting checks. Valibot could support that by accepting an option to skip all pipeline checks when parsing.
For example: 
```ts
const schema = object({
name: string(),
email: string([email()]),
});
const initialValues: unknown = { name: '', email: '' };
parse(schema, initialValues); // will throw
parse(schema, initialValues, { skipPipes: true }); // won't throw
```
This could be really useful in circumstances such as initial form values, where we do care about the type of the values, but want to run formatting checks separately.
If I understand …
=> Add option to skip pipelines when parsing

library/.eslintrc.cjs, library/package.json, library/src/utils/getPipeIssues/getPipeIssues.test.ts, library/src/validations/ulid/ulid.test.ts, library/src/validations/ulid/ulid.ts, pnpm-lock.yaml
I tried importing valibot from deno.land and had issues with ulid.ts missing the `.ts` in its imports.
It's easy enough to recreate the problem, just run `deno run https://deno.land/x/valibot@v0.17.0/mod.ts` in your shell today and you'll see the error. It's the same error when trying to use it as an import.
This PR fixes the issues with missing extensions and adds a new eslint rule to prevent it from happening again.
=> Fix deno import issue for missing file ext and add new linting rule

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Thanks to the last release and the better reflection API https://github.com/fabian-hiller/valibot/pull/211 I've been able to develop a pretty complete valibot to JSON schema CLI & JS library https://github.com/gcornut/valibot-json-schema/
=> Add `@gcornut/valibot-json-schema` to ecosystem

website/src/routes/guides/(get-started)/ecosystem/index.mdx
[`mantine-form-valibot-resolver`](https://github.com/Songkeys/mantine-form-valibot-resolver) is published to bring [`valibot`](https://github.com/fabian-hiller/valibot) to `@mantine/form`.
related: https://github.com/mantinedev/mantine/pull/5416
=> docs(ecosystem): add mantine-form-valibot-resolver to ecosystem

website/src/routes/api/(schemas)/symbol/index.mdx, website/src/routes/api/(types)/SymbolSchema/index.mdx, website/src/routes/api/menu.md
Implementing symbol schema docs as discussed in https://github.com/fabian-hiller/valibot/issues/287
=> docs(api): add and fill symbol schema docs

website/src/routes/api/(schemas)/nullable/index.mdx, website/src/routes/api/(schemas)/nullable/properties.ts, website/src/routes/api/(types)/NullableSchema/index.mdx, website/src/routes/api/(types)/NullableSchema/properties.ts, website/src/routes/api/menu.md
Hi! As mentioned in #287, here is the nullable docs (which is basically a copy-paste of `optional`), with the same examples as we discussed on discord
Added:
- `api/(types)/NullableSchema`: `NullableSchema` type definition
Edited:
- `api/(schemas)/nullable`: `nullable` usage & examples
- `api/menu.md`: Added `NullableSchema` in the types section
=> docs(api): Nullable related docs

website/src/routes/api/(schemas)/nullish/index.mdx, website/src/routes/api/(schemas)/nullish/properties.ts, website/src/routes/api/(types)/NullishSchema/index.mdx, website/src/routes/api/(types)/NullishSchema/properties.ts, website/src/routes/api/menu.md
Hi (again)! As mentioned in #287, here is the nullish docs (which is basically a copy-paste of `optional`), with the same examples as we discussed on discord
Added:
- `api/(types)/NullishSchema`: `NullishSchema` type definition
Edited:
- `api/(schemas)/nullish`: `nullish` usage & examples
- `api/menu.md`: Added `NullishSchema` in the types section
=> docs(api): Nullish related docs

website/src/routes/api/(schemas)/any/index.mdx, website/src/routes/api/(schemas)/bigint/index.mdx, website/src/routes/api/(schemas)/blob/index.mdx, website/src/routes/api/(schemas)/boolean/index.mdx, website/src/routes/api/(schemas)/date/index.mdx, website/src/routes/api/(schemas)/enum_/index.mdx, website/src/routes/api/(schemas)/instance/index.mdx, website/src/routes/api/(schemas)/picklist/index.mdx, website/src/routes/api/(schemas)/string/index.mdx, website/src/routes/api/(schemas)/symbol/index.mdx, website/src/routes/api/(schemas)/unknown/index.mdx, website/src/routes/api/(schemas)/unknown/properties.ts, website/src/routes/api/(types)/UnknownSchema/index.mdx, website/src/routes/api/(types)/UnknownSchema/properties.ts, website/src/routes/api/menu.md
Parent issue: https://github.com/fabian-hiller/valibot/issues/287
Created by referencing the `string()` doc. See if this is in the right direction. And whether I have missed anything on the related API part.
=> doc(api): add `unknown()` related doc

library/src/schemas/nonNullable/types.ts, library/src/schemas/nonNullish/types.ts, library/src/schemas/nonOptional/types.ts
On deno project, failed to import v0.27.0.
This PR fixes its missing extensions.
ref: https://github.com/fabian-hiller/valibot/commit/49fc7a76e7f42f04bf780f9d18e050c2ffee4fc1
=> fix(deno): fix missing extensions

library/CHANGELOG.md, library/src/schemas/recursive/recursive.test.ts, library/src/schemas/recursive/recursive.ts, library/src/schemas/recursive/recursiveAsync.test.ts, library/src/schemas/recursive/recursiveAsync.ts, library/src/types/other.ts, website/src/routes/api/(schemas)/recursive/properties.ts, website/src/routes/api/(types)/RecursiveSchema/properties.ts
Resolve #440 
Currently, when we aim to create a valibot schema that depends on real-time data, the following code snippet is a standard approach:
```ts
const input = {
// Your input here
};
const schema = v.recursive(() => {
if(input.type === 'A') {
return v.object({
foo: v.string()
});
}
return v.object({
Column: v.number()
});
});
const output = v.parse(schema, input);
```
However, this method presents challenges in abstracting the schema effectively.
If the `v.recursive()` function could accept a parameter—specifically, the second parameter passed to `parse()`—we would be able to abstract the schema with greater ease, as shown below:
```ts
// schema.ts
const schema = v.recursive((input) => {
if(input.type === 'A') {
return v.object({
foo: v.string()
});
}
return v.object({
Column: …
```
=> Add support for `input` as value in `v.recursive()` getter

packages/i18n/README.md
Thanks for adding link to PR with russian translation! However, despite the issue number is correct, the link leads to another PR. This PR changes the path to the correct one
=> chore(i18n): change PR link to russian translation

packages/i18n/package.json
valibot v0.29.0 has been released but installing with `@valibot/i18n` causes peer dependency failure because the package requires v0.28.x. This pull request adds support of valibot v0.29.x to the i18n package.
=> [i18n] Allow valibot v0.29 in peer dependencies

library/src/actions/includes/includes.test-d.ts, library/src/actions/includes/includes.test.ts, library/src/actions/includes/includes.ts, library/src/actions/includes/index.ts, library/src/actions/index.ts
There are a few things done differently which are summarized in the points below:
1. The `IncludesInput` type is inside the `includes` action file rather than in a shared types file like for `LengthInput`. I assume `LengthInput` will be reused for `minLength` and `maxLength` and therefore it makes sense to include it in the shared type file. I don't think `IncludesInput` will be reused for any other action.
2. The `_run` method of the action is handled differently because of the change in types of the parameters. Read the code comments for a detailed explanation.
3. The type tests contains a block that checks if the action function can relate input and requirement types properly. I am not sure if the written type tests for the block are ideal. Let me know if I should follow any good …
=> feat(rewrite-with-pipe): add includes action

library/src/actions/index.ts, library/src/actions/isoTime/isoTime.test.ts, library/src/actions/isoTimeSecond/index.ts, library/src/actions/isoTimeSecond/isoTimeSecond.test-d.ts, library/src/actions/isoTimeSecond/isoTimeSecond.test.ts, library/src/actions/isoTimeSecond/isoTimeSecond.ts
=> feat(rewrite-with-pipe): add `isoTimeSecond` validation

library/src/actions/index.ts, library/src/actions/isoWeek/index.ts, library/src/actions/isoWeek/isoWeek.test-d.ts, library/src/actions/isoWeek/isoWeek.test.ts, library/src/actions/isoWeek/isoWeek.ts
Part of #502
Note that some years, [like 2012, can have 54 weeks](https://www.timeanddate.com/calendar/custom.html?year=2012&country=9&cdt=1&typ=0&display=3&df=1).
=> feat(rewrite-with-pipe): add `isoWeek` action

website/src/routes/guides/(get-started)/installation/index.mdx
> [Migrating Deno modules from /x to JSR](https://jsr.io/docs/migrate-x-to-jsr)
--- 
Updated:
> **There are no plans to discontinue or shut down deno.land/x.** Module authors can continue to publish and update modules there, and Deno code using it will continue to function.
=> docs(installation): add jsr

library/src/schemas/variant/variant.ts, library/src/schemas/variant/variantAsync.ts
The `options` specified when generating a variant schema are curried. So I wrote this fix.
I don't think it's a good way to do it, but in my use case, if I want to make changes to the `options` below, it won't work without this fix. Since it works with other schemas, the `options` are specified differently only for variant schema.
```ts
const schema = variant('type', [
object({ type: literal('a'), value: string() }),
object({ type: literal('b'), value: number() }),
])
const convertSchema = {
...schema,
options: type.options.map((option) =>
pipe(
unknown(),
transform((output) => output.value == null ? { ...output, value: "" } : output),
option,
),
}
safeParse(convertSchema, { type: 'a', value: null }) // <-- parse error
```
=> Modify variant schema options reference more precise

.grit/.gitignore, .grit/grit.yaml, .grit/patterns/valibot_v03.md
You can try this out by running
```
grit apply valibot_v03
```
Grit also includes built-in testing for the markdown file. Just run `grit patterns test` in this repo.
=> Add Grit migration script

.grit/patterns/migrate_to_v0_31_0.md
We need to make sure the codemod doesn't rename methods that don't come from valibot.
=> fix: exclude unrelated names from codemod

.grit/patterns/migrate_to_v0_31_0.md
We use `sequential` to rerun the migration twice to catch cases where transform/pipe interact weirdly. Test cases cover everything discussed so far.
=> fix(grit): prevent nested pipes from being incorrectly rewritten

library/src/types/config.ts, library/src/utils/entriesFromList/entriesFromList.ts, library/src/vitest/expectNoActionIssue.ts, library/src/vitest/expectNoActionIssueAsync.ts, library/src/vitest/expectNoSchemaIssue.ts, library/src/vitest/expectNoSchemaIssueAsync.ts
Fixled some files that were imported without extensions.
When using `https://deno.land/x/valibot` with deno, the type check fails after updating to `v0.31.0`.
So, I fixed some files has `import` without extensions.
I checked this fixes by `deno check src/**/*.ts` on `Library` dir.
=> fix(deno): Add missing file extensions

library/CHANGELOG.md, library/src/schemas/looseTuple/looseTuple.ts, library/src/schemas/looseTuple/looseTupleAsync.ts, library/src/schemas/strictTuple/strictTuple.ts, library/src/schemas/strictTuple/strictTupleAsync.ts, library/src/schemas/tuple/tuple.ts, library/src/schemas/tuple/tupleAsync.ts, library/src/schemas/tupleWithRest/tupleWithRest.ts, library/src/schemas/tupleWithRest/tupleWithRestAsync.ts
The `items` specified when generating a tupleAsync schema are curried. So I wrote this fix.
This change is for the same reason as the previous change to the variant schema. #600 
I have created [code](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6GAFcwpPgEFUAT1ZMAFAG0MY1pJAU+UVQEoANOI5RgrAObGAukYbM2HOC1YYDMbv0Ei4AN70cHBiYT4CyCbBcMAwAqgAXHARgmJxCWKCYKqqGSBGIgB8gTEhWmDAYPJKKqplIeKSrADWrBAA7qzG0Y2NWjBQyOzY0CC5EJIwYFOFwiVBfX3uqBCyYqQQtoTt8HwAHnxMU3yERg19UHxSUKxwk9NTIqI6pKRwAPxwAAxwyQ8zGAXOAAX1MwPyvUa5xCYPoIMYKzWfA2W1UhA4yFgcDAWNQp3OK3gV1QklI8FEyA6yDi5mQ2D4AAU8TVlGp3J5YKkonB1K9SGZCPEOIQHAwketNts+KwACY4llnREuZGo2wkskwRxAA) that reproduces this issue.
```ts
import * as v from 'valibot';
const Schema = v.tupleAsync([v.number(), …
```
=> Modify tupleAsync schema items reference more precise

library/src/actions/partialCheck/index.ts, library/src/actions/rawCheck/index.ts, library/src/actions/rawTransform/index.ts
Some type exports are erased by TypeScript and break when using Deno as the runtime:
```
error: Uncaught SyntaxError: The requested module './types.ts' does not provide an export named 'PartialCheckIssue'
export { PartialCheckIssue } from './types.ts';
^
at <anonymous> (https://jsr.io/@valibot/valibot/0.33.1/src/actions/partialCheck/index.ts:3:10)
```
This PR fixes those exports
=> Use type exports where appropriate

website/src/routes/guides/(migration)/migrate-to-v0.31.0/index.mdx
Fix parenthesis typo on pipe example at documentation page
=> fix: parenthesis typo on pipe example

website/src/routes/api/(types)/CustomSchema/index.mdx, website/src/routes/api/(types)/CustomSchemaAsync/index.mdx, website/src/routes/api/(types)/CustomSchemaAsync/properties.ts
Also, is the "Special schema async type." description intentional? I think it should be "Custom schema async type."
=> add 'extends' to `CustomAsyncSchema` def of the API ref

website/src/routes/api/(async)/mapAsync/index.mdx, website/src/routes/api/(async)/mapAsync/properties.ts, website/src/routes/api/(types)/ArraySchemaAsync/index.mdx, website/src/routes/api/(types)/ArraySchemaAsync/properties.ts, website/src/routes/api/(types)/MapSchemaAsync/index.mdx, website/src/routes/api/(types)/MapSchemaAsync/properties.ts, website/src/routes/api/menu.md
This PR adds `mapAsync` & `MapSchemaAsync` to the documentation. Feel free to replace the example if you have a better one.
=> add `mapAsync` & `MapSchemaAsync` doc

website/src/routes/api/(async)/objectAsync/index.mdx, website/src/routes/api/(async)/objectAsync/properties.ts, website/src/routes/api/(types)/ObjectSchemaAsync/index.mdx, website/src/routes/api/(types)/ObjectSchemaAsync/properties.ts
This PR adds `objectAsync` and improves `ObjectSchemaAsync` API refs.
Question: The "Examples" section's description links to the [object guide](https://valibot.dev/guides/objects/) which contains sync examples and explanations. Do you think it is a good idea to add an [async guide](https://valibot.dev/guides/async-validation/) link too, so that the user is aware of the details related to asynchronous validation while reading the [object guide](https://valibot.dev/guides/objects/) page? Or can we assume that the user knows about async validation making the async guide link unnecessary? 
=> add `objectAsync` doc & improve `ObjectSchemaAsync` API ref

website/src/routes/api/(types)/InferSetInput/index.mdx, website/src/routes/api/(types)/InferSetInput/properties.ts, website/src/routes/api/(types)/InferSetOutput/index.mdx, website/src/routes/api/(types)/InferSetOutput/properties.ts
The `InferSetInput` and `InferSetOutput` types can also accept async set schemas. This PR adds this information to the API reference pages.
=> improve set input and output types API refs

website/src/routes/api/(async)/awaitAsync/index.mdx, website/src/routes/api/(async)/awaitAsync/properties.ts
Since `awaitAsync` did not have an equivalent sync action (which is obvious but mentioned for context), I had to fill in the "related" schemas, methods, and utils. So I might have made a mistake, especially relating some methods to `awaitAsync`. I'll share my thoughts:
- For schemas, it is straightforward, as I can use any schema after awaiting the `promise` schema. That means, every schema can be listed.
- For methods, I copied the list from the `promise` schema and separated the sync and async methods properly. I think if a user needs to check the resolved value of a promise, the user will have to use the `promise` schema along with the `awaitAsync` action always. Then can proceed using any combination of schemas, methods and actions. 
Let me know if the reasoning is flawed.
=> add `awaitAsync` API reference

library/CHANGELOG.md, library/src/methods/fallback/fallbackAsync.test.ts, library/src/methods/fallback/fallbackAsync.ts
This PR fixes the issue related to `fallbackAsync` given any async schema.
Issue:
When the validation of an async schema fails, `fallbackAsync` still returns the default value instead of the supplied fallback value. The code block given below exposes this bug.
```
import * as v from 'valibot';
const Schema = v.fallbackAsync(
v.pipeAsync(
v.string(),
v.checkAsync(async (value) => false)
),
"fallback"
);
// logs: default
console.log(await v.safeParseAsync(Schema, "default"));
```
Fix:
Inside the `_run` method of the object returned by `fallbackAsync`, wait for the schema to run completely before checking if the dataset has any issues. This is needed as `fallbackAsync` can be given an async schema that might execute some async code.
Additional information:
Simply waiting for the async code …
=> fix `fallbackAsync` for async arg & add relevant tests

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Code in this PR adds next-safe-action library to the ecosystem page, as suggested by Fabian in [this tweet](https://x.com/FabianHiller/status/1814702642141995460).
=> docs: add next-safe-action library to ecosystem page

website/src/routes/api/(async)/getFallbacksAsync/index.mdx, website/src/routes/api/(async)/getFallbacksAsync/properties.ts
I have used the same example that was added to `fallbackAsync` as I was unable to think of a better example. I'll try to come up with better examples once most of the API references are added. Feel free to update or add examples if you have something better. 
=> add `getFallbacksAsync` API reference

website/src/routes/api/(async)/objectAsync/index.mdx, website/src/routes/api/(schemas)/intersect/index.mdx
Improvements:
- Remove `intersect` from the related schemas section of the `intersect` schema.
- Add `object` to the related schemas section of the `objectAsync` schema as they are related.
=> improve `objectAsync` and `intersect` API refs

website/src/routes/api/(schemas)/lazy/index.mdx, website/src/routes/api/(schemas)/lazy/properties.ts
Improvements:
- Change the name and constraint of the type parameter.
- Change the type of the `getter` parameter.
- Update the name of the type argument of `LazySchema`.
- Recommend `GenericSchema` to explicitly specify types.
=> improve `lazy` API reference

website/src/routes/guides/(get-started)/ecosystem/index.mdx
This pull request adds a link to the valibot-env package in the documentation. I developed valibot-env to help with environment variables validation using Valibot, and I think this link will make it easier for users to find and use the package.
Thanks for your nice package!
=> docs: add valibot-env to guides/ecosystem

website/src/routes/api/(async)/parseAsync/index.mdx, website/src/routes/api/(async)/parseAsync/properties.ts
There is one change that might be unusual, and that is the note at the end of the 'Explanation' section. I thought it was needed as Valibot doesn't catch the errors thrown by some asynchronous operations.
=> add `parseAsync` API reference

website/src/routes/api/(async)/parserAsync/index.mdx, website/src/routes/api/(async)/parserAsync/properties.ts
I noticed the 'Explanation' section is missing under 'Parameters'. I assume this is because `parserAsync` returns a function instead of directly using the arguments to generate a final output. But I think an explanation like the one on [this](https://valibot.dev/api/parseAsync/) webpage is needed. Maybe we can add a similar explanation under the 'Returns' section. Good idea? 
=> add `parserAsync` API reference

website/src/routes/api/(async)/partialAsync/index.mdx, website/src/routes/api/(async)/requiredAsync/index.mdx, website/src/routes/api/(async)/requiredAsync/properties.ts, website/src/routes/api/(types)/SchemaWithRequiredAsync/index.mdx, website/src/routes/api/menu.md
The `requiredAsync` reference with this PR is a bit different from the `required` reference on the website. After this PR is merged, I'll make sure to update the `required` reference (if there are any changes needed). Here are the differences along with the reasons:
1. The `required` reference does not use a type parameter for the message parameter but the `requiredAsync` reference does. I think we should list `TMessage` so that: 
a. the reference is as close to the code as possible. 
b. we display the link between the `message` parameter and the output schema in the reference.
2. The naming of the output schemas. Instead of naming the output `Schema`, it is better to name the schemas `AllKeysSchema` and `SelectedKeysSchema` so that readers can identify the schemas in the 'Returns' …
=> add `requiredAsync` & `SchemaWithRequiredAsync` API refs

website/src/routes/api/(methods)/required/index.mdx, website/src/routes/api/(methods)/required/properties.ts, website/src/routes/api/(types)/SchemaWithRequired/index.mdx, website/src/routes/api/menu.md
Improvements:
- Rephrase the description
- Rename the output schema names
- Add a type parameter for the message parameter
- Improve the "Returns" section
- Add `SchemaWithRequired` API reference
- Sort "Related Actions" list
=> improve `required` API reference

website/src/routes/api/(async)/recordAsync/index.mdx, website/src/routes/api/(async)/recordAsync/properties.ts, website/src/routes/api/(async)/requiredAsync/index.mdx, website/src/routes/api/(types)/RecordSchemaAsync/index.mdx, website/src/routes/api/(types)/RecordSchemaAsync/properties.ts, website/src/routes/api/menu.md
I couldn't think of good examples that use `enum` or `picklist` schemas as key arguments. I will add those types of examples later (if not added by someone else).
=> add `recordAsync` & `RecordSchemaAsync` API refs

website/src/routes/guides/(get-started)/ecosystem/index.mdx
I'm deprecating the @gcornut/valibot-json-schema project as we now have an official JSON schema converter.
I moved the CLI interface to another package because I still needed this use case :)
=> Update JSON schema tools on ecosystem page

website/src/routes/api/(actions)/rawCheck/AddIssue/index.mdx, website/src/routes/api/(actions)/rawCheck/AddIssue/properties.ts, website/src/routes/api/(actions)/rawCheck/Context/index.mdx, website/src/routes/api/(actions)/rawCheck/Context/properties.ts, website/src/routes/api/(actions)/rawCheck/IssueInfo/index.mdx, website/src/routes/api/(actions)/rawCheck/IssueInfo/properties.ts, website/src/routes/api/(async)/rawCheckAsync/index.mdx, website/src/routes/api/(async)/rawCheckAsync/properties.ts, website/src/routes/api/(types)/RawCheckActionAsync/index.mdx, website/src/routes/api/(types)/RawCheckActionAsync/properties.ts, website/src/routes/api/menu.md
This PR adds `rawCheckAsync` and `rawCheckActionAsync` API references. While adding content, something was unclear to me. The question I asked myself was: Should I create a 'type' page (for example, [IntersectOptions](https://valibot.dev/api/IntersectOptions/)) for the `Context` type used by the only parameter of the function passed to this action, or should I inline the type? The `rawCheck` API reference inlined the type definition, and so I did the same. I assume the reason for inlining the type definition for the `rawCheck` API reference was to avoid polluting the 'types' section on the website with local types that are associated with maybe just one action so that we reduce the chances of naming collisions? For example, there is a `Context` type in the `_addIssue.ts` file. If someday …
=> add `rawCheckAsync` & `RawCheckActionAsync` API refs

packages/to-json-schema/src/index.ts
When I imported from `@valibot/to-json-schema` using JSR and Deno, I received an error.
Code:
```ts
import { toJsonSchema } from '@valibot/to-json-schema'
import { schema } from '../schema/schema.ts'
export const makeSchema = async () => {
const jsonSchema = toJsonSchema(schema)
await Deno.writeTextFile('schema.json', JSON.stringify(jsonSchema, null, 2))
}
if (import.meta.main) {
await makeSchema()
}
```
The PR will fixes it.
=> fix(to-json-schema): Error in JSR

website/src/routes/guides/(get-started)/ecosystem/index.mdx
I'm excited to introduce you to GQLoom.
[GQLoom](https://gqloom.dev/) is a GraphQL weaver for TypeScript/JavaScript that weaves GraphQL Schema and resolvers using Valibot, Zod, or Yup, and supports sophisticated type inference to provide the best development experience.
```ts
import { resolver, query, weave } from "@gqloom/valibot"
import * as v from "valibot"
const HelloResolver = resolver({
hello: query(v.string(), () => "world"),
})
export const schema = weave(HelloResolver)
```
=> Docs: add GQLoom to ecosystem

website/src/routes/guides/(advanced)/async-validation/index.mdx, website/src/routes/guides/(advanced)/internationalization/index.mdx, website/src/routes/guides/(advanced)/json-schema/index.mdx, website/src/routes/guides/(advanced)/naming-convention/index.mdx, website/src/routes/guides/(get-started)/comparison/index.mdx, website/src/routes/guides/(get-started)/ecosystem/index.mdx, website/src/routes/guides/(get-started)/installation/index.mdx, website/src/routes/guides/(get-started)/quick-start/index.mdx, website/src/routes/guides/(get-started)/use-cases/index.mdx, website/src/routes/guides/(main-concepts)/infer-types/index.mdx, website/src/routes/guides/(main-concepts)/issues/index.mdx, website/src/routes/guides/(main-concepts)/mental-model/index.mdx, website/src/routes/guides/(main-concepts)/methods/index.mdx, website/src/routes/guides/(main-concepts)/parse-data/index.mdx, website/src/routes/guides/(main-concepts)/pipelines/index.mdx, website/src/routes/guides/(main-concepts)/quick-start/index.mdx, website/src/routes/guides/(main-concepts)/schemas/index.mdx, website/src/routes/guides/(migration)/migrate-from-ajv/index.mdx, website/src/routes/guides/(migration)/migrate-from-joi/index.mdx, website/src/routes/guides/(migration)/migrate-from-yup/index.mdx, website/src/routes/guides/(migration)/migrate-to-v0.31.0/index.mdx, website/src/routes/guides/(schemas)/intersections/index.mdx, website/src/routes/guides/(schemas)/objects/index.mdx, website/src/routes/guides/(schemas)/optionals/index.mdx, website/src/routes/guides/(schemas)/other/index.mdx, website/src/routes/guides/(schemas)/unions/index.mdx
In line with #687, I have begun work towards the migration of the documentation from first-person to a more neutral tone. I was personally amused by the personality at first, but as suggested by many others, it did get old pretty quick.
This PR only adjusts the text for the Main Concepts section of the Guides page. There is a lot more work to do, but I'd like to keep this PR well-scoped in the meantime. Let me know if you have any concerns regarding the updated version of the text.
> [!NOTE]
> As an aside, I'd like to invite you in accepting this PR as a valid submission for this year's [Hacktoberfest](https://hacktoberfest.com/). There are [two ways](https://hacktoberfest.com/participation/) to do this: (1) add the `hacktoberfest` topic to the repository or (2) add the …
=> docs(website): migrate main concepts away from first-person

library/src/methods/forward/forward.ts, library/src/methods/forward/forwardAsync.ts, library/src/schemas/nonNullable/nonNullable.ts, library/src/schemas/nonNullable/nonNullableAsync.ts, library/src/schemas/nonNullish/nonNullish.ts, library/src/schemas/nonNullish/nonNullishAsync.ts, library/src/schemas/nonOptional/nonOptional.ts, library/src/schemas/nonOptional/nonOptionalAsync.ts
This fixes #925 
The `nonOptional` schema has not been `typed = true` when its wrapping schema becomes `typed = true`.
I did changed it to be typed.
=> Set `typed` = true when the wrapped schema of nonOptional is typed

website/src/routes/api/(actions)/value/index.mdx, website/src/routes/api/(actions)/value/properties.ts, website/src/routes/api/(types)/ValueAction/index.mdx
Improvements:
- add a missing type argument to the `ValueIssue` type in the `value` action page
- rename `ValueValidation` to `ValueAction` in the `ValueAction` page
=> improve `value` related API references

website/src/routes/guides/(schemas)/optionals/index.mdx
Improvements:
1. Replace `Input` and `Output` with `InferInput` and `InferOutput` in one of the examples.
2. Change the behavior of the `Dependent default values` example to enable TypeScript to infer the correct output type.
More information related to the 2nd improvement:
The example without the improvement does not work as [intended](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGEymBXU5DGBsAykwAWAUxDI4AXkwA6MMDCSAFPThKIFAFaSmMdQG8t2lAC4lrXiAqSo6gJQAac9orWMi2-ccu7hZwqHbeihBgQmxk6j5+Dk7ObuYAvinaPjBQyOzY0CDq6sCsYLwwzvIAfHBmwcDYcMWl5YqhBHKdcLysACaS2CWSvZV1wXBQkjC8UKy1cIqLJWUwriFhcMutsgDUmy0wihRwqQzBqR4TUzNzWzBnJ870zgz02QCeteYs7PC9gshrD0ANasCAAdzmChMgLgAEY1l44AAmNbtawAZlO3zYHCuoVI8AUPjAyCgqA03FIfAE0VYYikMjW-xgyBe5gA9By4AAVd5qOCOPBQOBSSY437rEDW …
=> improve `optionals` guide

website/src/routes/api/(actions)/minLength/index.mdx
Small typo in minLength documentation.  Update to 5 to match example.
=> Fix typo in minLength documentation

library/tsconfig.json, packages/i18n/tsconfig.json, packages/to-json-schema/tsconfig.json
Support for extremely modern ES syntax still isn’t universal, and is totally unnecessary for us, since the only diff this results in is
```diff
--- library/dist/index.js
+++ library/dist/index.js
@@ -237,8 +237,4 @@
var ValiError = class extends Error {
/**
-   * The error issues.
-   */
-  issues;
-  /**
* Creates a Valibot error with useful information.
*
```
(The .d.ts file is unaffected, so no documentation is lost.)
=> Reduce TypeScript target to ES2020

packages/to-json-schema/CHANGELOG.md, packages/to-json-schema/src/convertSchema.test.ts, packages/to-json-schema/src/convertSchema.ts, packages/to-json-schema/src/toJsonSchema.test.ts
`additionalProperties: true` was preventing validation of valid intersected objects.
- Fixes #990.
=> toJsonSchema: Only disallow additionalProperties for strictObject

packages/to-json-schema/CHANGELOG.md, packages/to-json-schema/src/convertAction.test.ts, packages/to-json-schema/src/convertAction.ts, packages/to-json-schema/src/convertSchema.ts
=> feat(json): added support for more schema and actions

website/src/routes/api/(actions)/base64/index.mdx, website/src/routes/api/(types)/Base64Action/index.mdx, website/src/routes/api/(types)/Base64Action/properties.ts
Improvements:
- Add a description to the `base64` page
- Add a missing link on the `Base64Action` page
=> improve `base64` & its action's API references

website/src/routes/api/(actions)/maxGraphemes/index.mdx
Each grapheme in text generated by the following sites (called zalgo text can be composed of over 100 characters, so you have to combine it with `maxLength` and so on.
https://zalgo.org/
https://lingojam.com/ZalgoText
Question: how can I add an admonition?
=> docs: Add warning about combining maxGraphemes with length limiters

library/CHANGELOG.md, library/src/utils/_addIssue/_addIssue.test.ts, library/src/utils/_addIssue/_addIssue.ts
Hello!
I'm using Valibot together with [`@vee-validate/valibot`](http://npmjs.com/@vee-validate/valibot) for form validation on frontend.
In some cases, I'd like to give some fields an empty error message to indicate that the form is invalid, but no error message should be shown to an end user.
Currently valibot skips custom empty error messages as if it's missing and uses the default error message instead.
This PR allows custom empty error messages, which I also think was the initial intention, given the final error message is constructed in such a way that it respects empty strings:
https://github.com/fabian-hiller/valibot/blob/f25b7c7e1621e918f2670f0ba5b8abcfbe7aa550/library/src/utils/_addIssue/_addIssue.ts#L105-L112
=> feat: allow custom error message to be empty

library/src/actions/email/email.ts, library/src/regex.ts
Fixes #1067
All tests passed by chance so I submit this PR.
Also I improved the description on `v.email()`. Readers will be able to know that it is compatible with `<input type="email">`.
=> Strip u flag in email regexp and improve description on v.email

library/CHANGELOG.md, library/src/actions/decimal/decimal.test.ts, library/src/regex.ts
=> Change DECIMAL_REGEX to support floats that start with a dot

website/src/components/PostCover.tsx
When hovering over the blog posts, the hover transition snaps into place.
Move the transition to the GPU by adding the CSS declaration `will-change: transform;`.
This makes the hover transition smooth and fixes the snapping.
The video demonstrates the snapping issue first and the fix afterwards:
https://github.com/user-attachments/assets/9ed766c9-3c9e-40f8-b1e7-e5a41483404c
=> style(website): fix hover transition

website/src/routes/playground/iframeCode.js
`Object.getPrototypeOf` can return `null` if the object passed to it has a `null` prototype. If that is the case, we can not access any properties on the `null` prototype.
Use optional chaining after getting the object's prototype to attempt to get the name of the prototype's constructor. Then check to see if `name` is a string before checking to see if the constructor's name is something we want to use in place of the value in the stringified result.
This fixes fabian-hiller/valibot#1114.
=> Fix stringification of objects with null prototype

website/src/routes/guides/(get-started)/ecosystem/index.mdx
The form library [Conform](https://github.com/edmundhung/conform) now officially supports valibots, so the description has been revised.
Until now, Conform required the use of a library called conform-to-valibot to use valibot, but this [Pull Request](https://github.com/edmundhung/conform/pull/876) has made it officially supported.
So I revised the description on the Ecosystem page.
=> docs: Changed the description of Conform on the EcoSystem page

website/src/routes/api/(actions)/isoDate/index.mdx
Following up a [discussion on Discord](https://discord.com/channels/1252985447273992222/1362417323478089789/1363277287507755119) this example shows how to use `v.isoDate` in combination with `v.minValue` to show how to validate that an incoming `v.string` is in the isoDate-Format and is after a certain point in time.
=> docs: add isoDate with minValue example

library/CHANGELOG.md, library/src/actions/nanoid/nanoid.test-d.ts, library/src/actions/nanoid/nanoid.test.ts, library/src/actions/nanoid/nanoid.ts, library/src/regex.ts, packages/to-json-schema/src/convertAction.ts, website/src/routes/api/(actions)/nanoid/index.mdx, website/src/routes/api/(actions)/nanoid/properties.ts
Looking at my old commit, I realized that the old regex was partially wrong due to ESLint autofix. The old regex was less strict and allowed for certain characters that are invalid in Nano ID.
This PR also standardizes all the types and interface with regards to Nano ID to PascalCase.
=> fix: update nanoid to be more accurate

packages/to-json-schema/CHANGELOG.md, packages/to-json-schema/src/convertAction.test.ts, packages/to-json-schema/src/convertAction.ts
this pr adds support for the examples field to the to-json-schema conversion in valibot.
when a valibot schema includes a `metadata` action with an `examples` property, this property will now be translated to the `examples` field in the outputted `JSONSchema`.
this enhances the richness of the generated json schemas, allowing valibot schema examples to be available for documentation or tooling that consumes json schema.
open to iterating on the implementation.
=> feat(to-json-schema): support examples field

website/src/routes/api/menu.md
This action belongs and is already included in the Async section, there's no need to list it twice under the Actions section as well.
=> Remove duplicate rawTransformAsync action

website/src/routes/guides/(get-started)/ecosystem/index.mdx
I have implemented Valibot support in `svelte-jsonschema-form`.
- [Docs](https://x0k.dev/svelte-jsonschema-form/validators/valibot/)
- Related PR https://github.com/x0k/svelte-jsonschema-form/pull/156
=> Add `svelte-jsonschema-form` to ecosystem page

codemod/zod-to-valibot/.gitignore, codemod/zod-to-valibot/src/utils.ts
I'm working on fixing the codemod and while doing so I found pretty hard working with it because you are going off the diff in the console (also since whitespace counts you can't even copy the new output if it's meant to change).
This is a small chore that makes everything easier to reason and work with: when we test something we also write the `_actual` transform to disk so that you can open it with your editor of choice, look at the diff and even copy paste the result once you are satisfied with it.
Obviously it's git-ignored so we don't flood the repo, it's just for debugging purpose.
=> chore: write output to disk when testing codemod

codemod/zod-to-valibot/__testfixtures__/or/input.ts, codemod/zod-to-valibot/__testfixtures__/or/output.ts, codemod/zod-to-valibot/src/test-setup.test.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/constants.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/index.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/or/index.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/or/or.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/schemas-and-links.ts
Currently migrating `or` produces a runtime error
```ts
import * as z from 'zod';
const Schema = z.string().or(z.number())
```
proudces
```ts
import * as v from "valibot";
const Schema = v.string()(v.number())
```
this fixes it migrating or to an union.
=> feat: add `or` migration

website/src/routes/api/(types)/InferNonNullableInput/index.mdx, website/src/routes/api/(types)/InferNonNullableOutput/index.mdx, website/src/routes/api/(types)/InferNonNullishInput/index.mdx, website/src/routes/api/(types)/InferNonNullishOutput/index.mdx, website/src/routes/api/(types)/InferNonOptionalInput/index.mdx, website/src/routes/api/(types)/InferNonOptionalOutput/index.mdx
This PR fixes minor typos in the Valibot documentation.
Replaces occurrences of **'sting'** with the correct spelling **'string'** in:
- InferNonNullableInput
- InferNonNullableOutput
- InferNonNullishInput
- InferNonNullishOutput
- InferNonOptionalInput
- InferNonOptionalOutput
Thanks for your awesome work on Valibot! 🛠️✨
=> docs: fix 'sting' typo to 'string' across multiple type inference examples

codemod/zod-to-valibot/__testfixtures__/object-extend/input.ts, codemod/zod-to-valibot/__testfixtures__/object-extend/output.ts, codemod/zod-to-valibot/__testfixtures__/object-merge/input.ts, codemod/zod-to-valibot/__testfixtures__/object-merge/output.ts, codemod/zod-to-valibot/__testfixtures__/object-passthrough/output.ts, codemod/zod-to-valibot/__testfixtures__/object-strict/output.ts, codemod/zod-to-valibot/__testfixtures__/object-strip/output.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/extend/extend.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/merge/merge.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/passthrough/passthrough.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/strict/strict.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/schemas-and-links.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/schemas/object/object.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/types.ts
Currently `strict` migrate to the wrong code as you can see from the test input and output:
input
```ts
import { z } from "zod";
const Schema1 = z.object({key: z.string()}).strict();
const Schema2 = z.object({key: z.string()}, {message: "some message"}).strict();
const Schema3 = z.object({key: z.string()}, {description: "some description"}).strict();
const Schema4 = z.object({key: z.string()});
const Schema5 = Schema4.strict();
```
output
```ts
const Schema1 = v.strictObject({key: v.string()});
const Schema2 = v.strictObject({key: v.string()}, "some message");
const Schema3 = v.pipe(v.object({key: v.string()}), v.description("some description"), v.strict());
const Schema4 = v.object({key: v.string()});
const Schema5 = v.pipe(Schema4, v.strict());
```
`v.strict()` is not a thing.
this is …
=> fix: properly migrate `strict` and `passthrough`

website/src/routes/guides/(migration)/migrate-from-zod/CodemodEditor.tsx
The playground was creating the ts parser but internally the codemod uses `api.jscodeshift` not `api.j` so it was actually using the js parser (thus failing to parse any TS...which you know it is kinda of important for valibot 😄)
=> fix: use the ts parser in website codemod playground

website/src/routes/guides/(get-started)/ecosystem/index.mdx
This should make Hey API more relevant when people search for things like "openapi valibot"
=> Update Hey API link to Valibot plugin

packages/i18n/CHANGELOG.md, packages/i18n/README.md
Minor fix:
The country is **Indonesia** and the language is **Indonesian**.
=> fix(i18n): fix typo for Indonesian lang

website/src/routes/api/(types)/DeepPickN/index.mdx
This PR fixes an inaccurate `[source code]` reference link in the documentation for the `DeepPickN` API.
=> docs: fix source code reference link for DeepPickN

codemod/zod-to-valibot/__testfixtures__/multiple-imports-from-zod/input.ts, codemod/zod-to-valibot/__testfixtures__/multiple-imports-from-zod/output.ts, codemod/zod-to-valibot/__testfixtures__/refine/input.ts, codemod/zod-to-valibot/__testfixtures__/refine/output.ts, codemod/zod-to-valibot/__testfixtures__/transform/input.ts, codemod/zod-to-valibot/__testfixtures__/transform/output.ts, codemod/zod-to-valibot/src/test-setup.test.ts, codemod/zod-to-valibot/src/transform/imports/imports.ts, codemod/zod-to-valibot/src/transform/index.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/constants.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/index.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/refine/index.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/refine/refine.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/transform/index.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/methods/transform/transform.ts, codemod/zod-to-valibot/src/transform/schemas-and-links/schemas-and-links.ts
Some other small codemod fixes: this fixes `transform`, `refine` and adds a comment to explain why it's not possible to migrate the file when there's multiple zod imports (i also think we could try to be a bit smarter here and still migrate if at least one import is `z` from `zod` but that would lead to squiggles in the file unless we also replace all the zod types)
=> feat: graceful multiple imports exit + `transform` and `refine`

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Expands the **X → Valibot** section with two community tools for Prisma and Drizzle users:
- **[Prisma Valibot Generator](https://github.com/omar-dulaimi/prisma-valibot-generator)** — generates Valibot validators directly from a Prisma schema.
- **[DRZL](https://github.com/use-drzl/drzl)** — analyzes Drizzle ORM schema(s) and outputs Valibot validators, typed services, and strongly typed routers (oRPC/tRPC/etc).
=> docs: add prisma-valibot-generator & drzl to “X → Valibot” ecosystem

website/src/routes/guides/(get-started)/ecosystem/index.mdx
Hello Valibot maintainers!
This PR adds 2 libraries to the ecosystem:
1. [@traversable/valibot](https://github.com/traversable/schema/tree/main/packages/valibot)
2. [@traversable/valibot-test](https://github.com/traversable/schema/tree/main/packages/valibot-test)
These libraries were primarily built for developers who are building tools on top of Valibot, but can also be used for one of the 10+ off-the-shelf transformers that we currently support.
Happy to talk more about the library if you have any questions!
=> doc: adds `@traversable/valibot` and `@traversable/valibot-test` to ecosystem

packages/i18n/README.md
This is a small change to the i18n readme to fix the link for the Catalan PR. It incorrectly points to the Arabic PR.
=> chore: fix PR link for Catalan language entry
